"""improve clients table

Revision ID: c7ea936b2e5d
Revises: 557bad752e83
Create Date: 2025-05-23 07:44:27.408864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7ea936b2e5d'
down_revision: Union[str, None] = '557bad752e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('cpf', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'clients', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'cpf')
    # ### end Alembic commands ###
